services:
  - type: web
    name: shophere-in
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
    autoDeploy: true
